version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: ./php.Dockerfile
    tty: true
    links:
      - redis
    volumes:
      - ./:/var/www
  swoole:
    build:
      context: .
      dockerfile: ./swoole.Dockerfile
    tty: true
    links:
      - redis
    volumes:
      - ./:/var/www
  redis:
    image: redis
