name: Build Docker Images

on:
  push:
    branches:
      - master

jobs:
  build_docker_image:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        docker:
          - {type: "php", tag: "php-only"}
          - {type: "swoole", tag: "swoole-enabled"}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image deminy/counit:${{ matrix.docker.tag }}
        uses: docker/build-push-action@v5
        with:
          context: ./dockerfiles/${{ matrix.docker.type }}
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
          push: true
          tags: deminy/counit:${{ matrix.docker.tag }}
