name: Unit Tests

on: [ push, pull_request, workflow_dispatch ]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        phpunit: ["~8.0.0", "~8.0", "~9.0.0", "~9.0"]

    name: Run Unit Tests With PHPUnit ${{ matrix.phpunit }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Services
        run: |
          docker-compose up --build -d
          docker ps -a
          docker exec -t $(docker ps -qf "name=swoole") sh -c "composer require phpunit/phpunit ${{ matrix.phpunit }} --dev -n"

      - name: Run Unit Tests
        run: |
          set -ex
          docker exec -t $(docker ps -qf "name=swoole") sh -c "./vendor/bin/phpunit"
          docker exec -t $(docker ps -qf "name=php")    sh -c "./counit"
          docker exec -t $(docker ps -qf "name=swoole") sh -c "./counit"

      - name: Stop and Remove Docker Containers
        run: docker-compose down
